development:
  adapter: sqlite3
  database: ../db.sqlite3
production:
  adapter: postgresql
  database: d4rf7nl2e1r6pg
  username: pdwetbvgommdrq
  password: LXPNzir4jQBRkqsvGMenVSD5uX
  host: ec2-54-243-199-137.compute-1.amazonaws.com
